# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Yuya Jeremy Ong
tagline:	''
description: ''
url:		http://yutarochan.github.io

author:
  name:		Yuya Jeremy Ong
  url:		https://yutarochan.github.io

paginate:	5

menu:
  - title:	Home
    url:	/

  - title:	Blog
    url:	/blog

# Custom vars
copyright:
  author:	Yuya Jeremy Ong
  url:		http://yutarochan.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
