# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Yuya Jeremy Ong
tagline:	'Blog'
description:'Personal blog and profile site of Yuya Jeremy Ong.'
url:		http://yutarochan.github.io

author:
  name:		Yuya Jeremy Ong
  url:		https://yutarochan.github.io

paginate:	5

# Custom vars
icon:		/assets/images/profile.jpg
cover:		/assets/images/cover.jpeg

social:
  - icon:	twitter
    url:	https://twitter.com/YuyaJOng
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/yutarochan
    desc:	Fork me on github

  - icon:	feed
    url:	http://yutarochan.github.io/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	Yuya Jeremy oNg
  url:		http://yutarochan.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
