
# SEO settings
title: "Amaranth's "
title2: " Anomaly " # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Yuya, Jeremy, Ong, Deep Leaning, Artificial Intelligence, Computer Vision, Affective Computing"
url: http://heiswayi.github.io/thinkspace # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-74785105-1
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "yutarochan"
twitter_username: "yutarochan"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Yuya Ong"
  job      : "Data Scientist and Human"
  bio      : "He that would know what shall be, must consider what has been."
  thumb    : /images/author.jpg
  email    : yuyajeremyong@gmail.com
  url      : http://yutarochan.github.io
  github   : http://github.com/yutarchan
  linkedin : https://www.linkedin.com/in/yuya-ong-48a58527/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@yutarochan"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : work
    title: Work
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
